# Generated by Django 4.0.4 on 2022-07-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
