# Generated by Django 4.0.6 on 2022-12-29 04:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='default-image.png', null=True, upload_to=''),
        ),
    ]
